import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Buttons from "../components/Buttons.jsx";
import CurrentUser from "@/components/CurrentUser";
import Logo from "@/components/Logo";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-black`}
      >
        {/* Everything above footer */}
        <div className="flex-grow">
          <div className="w-full p-4">
            {/* Header section */}
            <div className="w-full flex flex-row justify-between items-center px-4 sm:px-6 py-3 mb-4">
              <Logo />
              <CurrentUser />
            </div>

            {/* Buttons section */}
            <Buttons />
          </div>

          {/* Page content */}
          {children}
        </div>

        {/* Sticky Footer */}
        <footer className="mt-16 pb-10 text-center text-gray-400 bg-black">
          <div className="flex justify-center items-center gap-2 mt-2">
            <Image
              alt="github"
              src="/github-svgrepo-com.svg"
              height={22}
              width={22}
              className="invert opacity-90"
            />
            <a
              href="https://github.com/AbhayPatil2004"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-300 hover:underline"
            >
              github.com/AbhayPatil2004
            </a>
          </div>

          <p className="mt-3 text-sm text-gray-500">
            &copy; {new Date().getFullYear()} NotesShare. All rights reserved.
          </p>
        </footer>
      </body>
    </html>

  );
}
